name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-pipeline:
    uses: tuempresa/tuempresapipelines/.github/workflows/pipeline.yaml@main
    with:
      script_path: your-script.sh
